spring:
  application:
    name: poitext
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatistext?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  jpa:
    show-sql: true
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8